version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:password@postgres:5432/todolist"
      PORT: 8000
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: todo_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
